[package]
name = "gomoku"
version = "0.1.0"
authors = ["afaucher17 <aymeric.faucher@gmail.com>", "tdieumeg <tdieumeg@users.noreply.github.com>"]
documentation = "https://afaucher17.github.io/gomoku/gomoku"
readme = "README.md"
keywords = ["gomoku", "gobang"]

[[bin]]
name = "gomoku"
doc = false

[features]
unstable = [] # for travis-cargo

[dependencies]
piston_window = "0.44.0"
find_folder = "0.3.0"
itertools = "0.4"
rand = "0.3"
time = "*"
piston = "0.23.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.27.0"
piston2d-opengl_graphics = "0.30.0"
