[package]
name = "gomoku"
version = "0.1.0"
authors = ["afaucher17 <aymeric.faucher@gmail.com>", "tdieumeg <tdieumeg@users.noreply.github.com>"]
description = "Gomoku is an abstract strategy board game. Also called Gobang or Five in a Row, it is traditionally played with Go pieces (black and white stones) on a go board with 19x19 (15x15) intersections; however, because once placed, pieces are not moved or removed from the board; gomoku may also be played as a paper and pencil game. This game is known in several countries under different names. (Wikipedia)"
documentation = "https://afaucher17.github.io/gomoku/gomoku"
readme = "README.md"
keywords = ["gomoku", "gobang"]

[[bin]]
name = "gomoku"
doc = false

[features]
unstable = [] # for travis-cargo

[dependencies]
itertools = "0.4"
rand = "0.3"
time = "*"
piston = "0.23.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.27.0"
piston2d-opengl_graphics = "0.30.0"
